name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

    name: "Build"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Prepare"
        run: |
          corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm

      - name: Install
        run: |
          pnpm install --frozen-lockfile

      - name: Lint
        run: |
          pnpm run lint

      - name: Build
        run: |
          pnpm run build

      - name: Test
        run: |
          pnpm test
